---
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v14
      with:
        config: '.github/workflow/config/custom.markdownlint.jsonc'
        globs: '**/*.md'
